name: Lupi
main: org.halvors.lupi.Lupi
version: 0.0.1
description: Lupi is a wolf plugin for Bukkit.
authors: [halvors, speeddemon92, adamonline45]
website: https://github.com/halvors/Lupi
database: true
load: startup
softdepend: [Spout]
commands:
    wolf:
        aliases: [lupi]
        description: Lupi commands.
        usage: |
            /<command> - Show a list of your wolves.
            /<command> help - Show help.
            /<command> list <player> - List all tamed wolves.
            /<command> info <wolf> - Show info about the wolf.
            /<command> setname <name> - Set the selected wolf's name.
            /<command> call <wolf> - Call your wolf.
            /<command> stop <wolf> - Stop your wolf from attacking.
            /<command> give <wolf> <player> - Give your wolf to an other player.
            /<command> release <wolf> - Release your wolf.
            
permissions:
    lupi.*:
        default: op
        description: Allows use of all Lupi features.
        children:
            lupi.admin.*: true
            lupi.wolf.*: true
    
    lupi.admin.*:
        description: Allows use of Lupi admin features.
        children:
            lupi.admin.reload: true
    
    lupi.admin.reload:
        description: Allows use of /wolf reload.
    
    lupi.wolf.*:
        description: Allows use of Lupi wolf features.
        children:
            lupi.wolf.select: true
            lupi.wolf.inventory: true
            lupi.wolf.armor: true
            
            lupi.wolf.help: true
            lupi.wolf.list: true
            lupi.wolf.info: true
            lupi.wolf.name: true
            lupi.wolf.setname: true
            lupi.wolf.call: true
            lupi.wolf.stop: true
            lupi.wolf.give: true
            lupi.wolf.release: true
            
    lupi.wolf.select:
        description: Allows you to select a wolf.
    lupi.wolf.inventory:
        description: Allows use of wolf inventory.
    lupi.wolf.armor:
        description: Allows use of wolf armor.  
        
    lupi.wolf.help:
        description: Allows viewing of usage for /wolf.
    lupi.wolf.list:
        description: Allows use of /wolf list.
    lupi.wolf.info:
        description: Allows you to view info about a wolf.
    lupi.wolf.setname:
        description: Allows use of /wolf setname.
    lupi.wolf.call:
        description: Allows use of /wolf call.
    lupi.wolf.stop:
        description: Allows use of /wolf stop.
    lupi.wolf.give:
        description: Allows use of /wolf give.
    lupi.wolf.release:
        description: Allows use of /wolf release.
