name: Lupi
main: org.halvors.lupi.Lupi
version: 0.1
description: Lupi is a wolf plugin for Bukkit.
authors: [halvors, speeddemon92, adamonline45]
website: 
database: true
load: startup

commands:
    wolf:
        description: Lupi commands.
        aliases: [lupi]
        usage:
