name: Lupi
main: org.halvors.lupi.Lupi
version: 0.0.1
description: Lupi is a wolf plugin for Bukkit.
authors: [halvors, speeddemon92, adamonline45]
website: 
database: true
load: startup

commands:
    wolf:
	aliases: [lupi]
        description: Lupi commands.
        usage: |
            /<command> - reload the configuration from disk.
            /<command> help - check if a player has a permission (any plugin).
            /<command> list - list group-related commands.
            /<command> group list - list all groups.
            /<command> group players <group> - list players in a group.
            /<command> group addperm <group> <node> - add a permission to a group.
            /<command> group removeperm <group> <node> - remove a permission from a group.
            /<command> player - list player-related commands.
            /<command> player groups <player> - list groups a player is in.
            /<command> player addgroup <player> - add a player to a group.
            /<command> player removegroup <player> - remove a player from a group.
            /<command> player addperm <player> <node> - add a permission to a player.
            /<command> player removeperm <player> <node> - remove a permission from a player.

permissions:
    lupi.*:
        children:
            lupi.help: true
            lupi.list: true
            lupi.wolf.*: true

    lupi.wolf.*:
        children:
            lupi.wolf.select: true
            lupi.wolf.info: true
            lupi.wolf.inventory: true
