name: Wolf
main: com.halvors.wolf.WolfPlugin
version: 0.1
description: Wolf is a wolf plugin for Bukkit.
authors: [halvors, speeddemon92]
website: 
database: true

commands:
    wolf:
        description:
        usage: