name: Lupi
main: com.halvors.lupi.Lupi
version: 0.1
description: Lupi is a wolf plugin for Bukkit.
authors: [halvors, speeddemon92]
website: 
database: true
load: startup

commands:
    wolf:
        description: Command for Wolf.
        aliases: [lupi]
        usage:

