# Wolf's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

item_select: 352
item_inventory: 352

autoaddtamedwolves: true

limit:
    enable: false # Enable limit of tamed wolves?
    value: 16 # Value, if limit is enabled.

wolf:
    enable: true # Allow wolves to spawn.
    inventory: true # Enable wolf inventory?
    pvp: true

