# Wolf's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

item: 352 # Item for select wolf

wolf:
    enable: true # Allow wolves to spawn.
    inventory: true # Enable wolf inventory?

    #respawn: true # Respawn tamed wolves.
    #peaceful: false # Wild wolves are peaceful.

    limit:
        enable: false # Enable limit of tamed wolves?
        limit: 16 # Limit count, if limit is enabled.