# Wolf's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

wolf:
    enable: true # Allow wolves to spawn.
    item: 352 # Item to select tamed wolves.
    pvp: false # Set wolf to not attack players when pvp is off.
    limit: 0 # Enable limit? 0 for disable and 1 or higher to enable.

inventory:
    enable: true # Use wolf inventory?
    item: 352 # Item for open/add wolf inventory.