# Wolf's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

item: 352 # Item for select wolf

wolf:
    enable: true # Allow wolves to spawn
    respawn: true # Respawn tamed wolves
    peaceful: false # Wolves are peaceful.
    limit: 0 # 0 to disable.