# Wolf's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

wolf:
    enable: true # Allow wolves to spawn.
    item: 352 # Item for select tamed wolves.
    pvp: false # Set wolf to not attack players when pvp is off

limit:
    enable: false # Enable limit of tamed wolves?
    value: 16 # Value, if limit is enabled.

inventory:
    enable: true # Use wolf inventory?
    item: 352 # Item for open/add wolf inventory.