# Wolf's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

item_select: 352
item_inventory: 352

    autoaddtamedwolves: true

wolf:
    enable: true # Allow wolves to spawn.
    inventory: true # Enable wolf inventory?

    #respawn: true # Respawn tamed wolves.

    limit:
        enable: false # Enable limit of tamed wolves?
        limit: 16 # Limit count, if limit is enabled.